preprocessing:
  batch_size: 32
  classes:
  - toxic
  - severe_toxic
  - obscene
  - threat
  - insult
  - identity_hate
  input_convertor: count_vectorization
  input_id_column: id
  input_testset: ./data/mini_test.csv
  input_text_column: comment_text
  input_trainset: ./data/mini_train.csv
  maxlen: 128
  random_seed: 0
  skip_tokenization: false
  split_ratio: 0.3
training:
  batch_normalization: true
  batch_size: 32
  dropout_rate: 0.5
  embedding_dim: 128
  epochs: 1
  gradient_cliping: true
  learning_rate: 1.0
  maxlen: 128
  model_name: naivebayes
  optimizer: sgd
  output_path: ./output
  predict_only: false
predict:
  calibrator_type: platt_scaling
  calibrators_output_path: ./output
  classes:
  - toxic
  - severe_toxic
  - obscene
  - threat
  - insult
  - identity_hate
  debug_validation: false
  enable_calibration: false
  output_path: ./data/submission.csv
